
INSERT INTO stampee.image (id, nom, timbre_id, adresse, est_principale) VALUES 
(null, 'tatoire Enflé', 1, '/img/timbres/timbre4.webp', 0),
(null, 'plein aux as Lit', 2, '/img/timbres/catalogue_Brazil-CA-DP3_2-253x300.webp', 1),
(null, 'logique Éléguant', 3, '/img/timbres/timbre6.webp', 1),
(null, 'Défigurable Sauté', 4, '/img/timbres/catalogue_Brazil-CA-DP3_2-253x300.webp', 1),
(null, 'sentatoire Enflé', 6, '/img/timbres/timbre3.webp', 1),
(null, 'entatoire Enflé', 7, '/img/timbres/catalogue_canada-stamp-117a-king-george-v-10-1922.webp', 1),
(null, 'magique Ancien', 9, '/img/timbres/catalogue_Brazil-CA-DP3_2-253x300.webp', 1),
(null, 'Abénéfique Petit', 10, '/img/timbres/timbre6.webp', 1),
(null, 'magique Gros', 11, '/img/timbres/timbre1.webp', 1),
(null, 'plein aux as Li', 12, '/img/timbres/timbre6.webp', 1),
(null, 'Plusieurs aristocratiques', 13, '/img/timbres/timbre3.webp', 1),
(null, 'parfois Filantropique', 107, '/img/timbres/catalogue_china-lot-black_0003-–-kopija.webp', 1),
(null, 'féérique Boursuflée', 108, '/img/timbres/catalogue_Brazil-CA-DP3_2-253x300.webp', 1),
(null, 'basique Timbre', 109, '/img/timbres/timbreCA.webp', 1),
(null, 'Logique Éléguante', 110, '/img/timbres/timbreCA.webp', 1),
(null, 'Abénéfique Amérique', 111, '/img/timbres/catalogue_canada-stamp-117a-king-george-v-10-1922.webp', 1),
(null, 'Défigurable Sauvé', 112, '/img/timbres/catalogue_brasilFootbal.webp', 1),
(null, 'Abénéfique sud', 113, '/img/timbres/timbre2.webp', 1),
(null, 'De bonne augure Qui peut', 114, '/img/timbres/timbre5.webp', 1),
(null, 'Gérable Timide', 115, '/img/timbres/timbre1.webp', 1),
(null, 'féérique Boursuflé', 116, '/img/timbres/catalogue_Brazil-CA-DP3_2-253x300.webp', 1),
(null, 'ntatoire Enflé', 117, '/img/timbres/catalogue_canada-stamp-214-prince-of-wales-5-1935.webp', 1),
(null, 'discutable Aléatoires', 118, '/img/timbres/catalogue_Brazil-CA-DP3_2-253x300.webp', 1),
(null, 'Défigurable Sacha', 119, '/img/timbres/catalogue_Argentina-1924-50c-stamp-plate-error.webp', 1),
(null, 'discutable vléatoire', 120, '/img/timbres/catalogue_canada-stamp-214-prince-of-wales-5-1935.webp', 1),
(null, 'parfois drôle Filantropique', 121, '/img/timbres/timbre2.webp', 1),
(null, 'Petit bénéfique', 122, '/img/timbres/timbre5.webp', 1),
(null, 'Permettr il faudra demain', 123, '/img/timbres/catalogue_canada-stamp-214-prince-of-wales-5-1935.webp', 1),
(null, 'Timid avant de tout remttre
', 124, '/img/timbres/timbreCA.webp', 1),
(null, 'Permettra il faudra quoi', 125, '/img/timbres/timbre5.webp', 1),
(null, 'Gargantuesque agrandissements de celui', 126, '/img/timbres/timbre2.webp', 1),
(null, 'Aléas il faudra un', 127, '/img/timbres/timbre4.webp', 1),
(null, 'Timbre douceur', 128, '/img/timbres/catalogue_Brazil-CA-DP3_2-253x300.webp', 1),
(null, 'Petites est exellentes', 129, '/img/timbres/timbre6.webp', 1),
(null, 'Gargantuesques agrandissements', 130, '/img/timbres/catalogue_Brazil-CA-DP3_2-253x300.webp', 1),
(null, 'Permettra il faudrait', 131, '/img/timbres/timbre3.webp', 1),
(null, 'Qui peut mais  ou il va?
', 132, '/img/timbres/catalogue_canada-stamp-117a-king-george-v-10-1922.webp', 1),
(null, 'Sauvé pour qui', 133, '/img/timbres/catalogue_Brazil-CA-DP3_2-253x300.webp', 1),
(null, 'Enflé pour impressionner les plus ardus', 134, '/img/timbres/timbre6.webp', 1),
(null, 'Filantropique sil te plaitu en a ', 135, '/img/timbres/timbre1.webp', 1),
(null, 'Grosse pourqui
', 136, '/img/timbres/timbre6.webp', 1),
(null, 'Timbre avec beaucoup de douceur', 137, '/img/timbres/timbre3.webp', 1),
(null, 'Grosses pourqui
', 138, '/img/timbres/catalogue_china-lot-black_0003-–-kopija.webp', 1),
(null, 'Aléo il faudra un deuxième', 139, '/img/timbres/catalogue_Brazil-CA-DP3_2-253x300.webp', 1),
(null, 'Timide avant de tout remttre', 140, '/img/timbres/timbreCA.webp', 1),
(null, 'Qui peut mais  ou il vont', 141, '/img/timbres/timbreCA.webp', 1),
(null, 'Sauvés pour qui', 142, '/img/timbres/catalogue_canada-stamp-117a-king-george-v-10-1922.webp', 1),
(null, 'Filantropique?te plait ', 143, '/img/timbres/catalogue_brasilFootbal.webp', 1),
(null, 'Lié allant au terme', 144, '/img/timbres/timbre2.webp', 1),
(null, 'Filantropiques', 145, '/img/timbres/timbre5.webp', 1),
(null, 'Plusieurs avant den arriver à lire', 146, '/img/timbres/timbre1.webp', 1),
(null, 'Enflé pour impressionner les plus ancien', 147, '/img/timbres/catalogue_Brazil-CA-DP3_2-253x300.webp', 1),
(null, 'Permettra il faudrait?', 148, '/img/timbres/catalogue_canada-stamp-214-prince-of-wales-5-1935.webp', 1),
(null, 'Petites est exellent', 149, '/img/timbres/catalogue_Brazil-CA-DP3_2-253x300.webp', 1),
(null, 'Boursuflé mais toujours aussi changé', 150, '/img/timbres/catalogue_Argentina-1924-50c-stamp-plate-error.webp', 1),
(null, 'Boursuflé mais toujours aussi déterminé', 151, '/img/timbres/catalogue_canada-stamp-214-prince-of-wales-5-1935.webp', 1),
(null, 'Petites est exellente', 152, '/img/timbres/timbre2.webp', 1),
(null, 'Gros pourquoi', 153, '/img/timbres/timbre5.webp', 1),
(null, 'Boursuflées et toujours aussi efficaces', 154, '/img/timbres/catalogue_canada-stamp-214-prince-of-wales-5-1935.webp', 1),
(null, 'Petits est exellent', 155, '/img/timbres/timbreCA.webp', 1),
(null, 'Qui peut mais  ou il
', 156, '/img/timbres/timbre5.webp', 1),
(null, 'Qui peut mais 
pourquoi ', 157, '/img/timbres/timbre2.webp', 1),
(null, 'Boursuflés mais toujours aussi efficaces', 158, '/img/timbres/timbre4.webp', 1),
(null, 'Plusieurs avant den arriver à pleurer', 159, '/img/timbres/catalogue_Brazil-CA-DP3_2-253x300.webp', 1),
(null, 'Qui peut mais va ', 160, '/img/timbres/timbre6.webp', 1),
(null, 'Plusieurs avant den arriver à dire', 161, '/img/timbres/catalogue_Brazil-CA-DP3_2-253x300.webp', 1),
(null, 'Boursuflées mais toujours aussi efficaces', 162, '/img/timbres/timbre3.webp', 1),
(null, 'Filantropiques si', 163, '/img/timbres/catalogue_canada-stamp-117a-king-george-v-10-1922.webp', 1),
(null, 'Qui peut mais tire ', 164, '/img/timbres/catalogue_Brazil-CA-DP3_2-253x300.webp', 1),
(null, 'Boursuflé mais toujours aussi efficaces', 165, '/img/timbres/timbre6.webp', 1),
(null, 'Gargant agrandissements', 166, '/img/timbres/timbre1.webp', 1),
(null, 'Gargantuesque agrandissements poursuit
', 167, '/img/timbres/timbre6.webp', 1),
(null, 'Lié allant au', 168, '/img/timbres/timbre3.webp', 1),
(null, 'Boursuflé mais toujours aussi efficace', 169, '/img/timbres/catalogue_china-lot-black_0003-–-kopija.webp', 1),
(null, 'Enflé pour impressionner les plus efficaces', 170, '/img/timbres/catalogue_Brazil-CA-DP3_2-253x300.webp', 1),
(null, 'Filantropiques jaloue', 171, '/img/timbres/timbreCA.webp', 1),
(null, 'Sauver pour qui moi', 172, '/img/timbres/timbreCA.webp', 1),
(null, 'Sauvergarder celui qui croyait', 173, '/img/timbres/catalogue_canada-stamp-117a-king-george-v-10-1922.webp', 1),
(null, 'Petite est exellente', 174, '/img/timbres/catalogue_brasilFootbal.webp', 1),
(null, 'mais qui peut  ', 175, '/img/timbres/timbre2.webp', 1),
(null, 'Aléatoire il faudra deux', 176, '/img/timbres/timbre5.webp', 1),
(null, 'Sauvergarder pour quoi', 177, '/img/timbres/timbre1.webp', 1),
(null, 'Aléatoire il faudra un', 178, '/img/timbres/catalogue_Brazil-CA-DP3_2-253x300.webp', 1),
(null, 'Gros pourqui
', 179, '/img/timbres/catalogue_canada-stamp-214-prince-of-wales-5-1935.webp', 1),
(null, 'Gros pour qui', 180, '/img/timbres/catalogue_Brazil-CA-DP3_2-253x300.webp', 1),
(null, 'Enflé pour impressionner les plus gentils', 181, '/img/timbres/catalogue_Argentina-1924-50c-stamp-plate-error.webp', 1),
(null, 'Gargants agrandissements', 182, '/img/timbres/catalogue_canada-stamp-214-prince-of-wales-5-1935.webp', 1),
(null, 'Gargantuesque agrandissement de celui qui', 183, '/img/timbres/timbre2.webp', 1),
(null, 'Petits est exellents', 184, '/img/timbres/timbre5.webp', 1),
(null, 'Permettre il faudra', 185, '/img/timbres/catalogue_canada-stamp-214-prince-of-wales-5-1935.webp', 1),
(null, 'Éléguant de ce timbre', 186, '/img/timbres/timbreCA.webp', 1),
(null, 'Aléatoires il faudra un', 187, '/img/timbres/catalogue_canada-stamp-117a-king-george-v-10-1922.webp', 1),
(null, 'Sauvergarder pour qui', 188, '/img/timbres/catalogue_Brazil-CA-DP3_2-253x300.webp', 1),
(null, 'Aléa il faudra un', 189, '/img/timbres/timbre6.webp', 1);